version: '3.7'
services:
  redis:
    image: redis:alpine
    command:
      - redis-server
    env_file:
      - ./.env
    restart: on-failure
    ports:
      - '6379:6379'
  db:
    image: sqlite3
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/sqlite3/data
    restart: on-failure
    ports:
      - '5432:5432'
  bot:
    build:
      dockerfile: Dockerfile
    command: sh -c 'make migrate && python -m bot'
    env_file:
      - ./.env
    restart: always
    depends_on:
      - db
      - redis

volumes:
  pgdata: